version: "3.7"
services:
    db:
        image: "mariadb:bionic"
        restart: always
        ports:
            - "3306:3306" # allow DB connections from host
        volumes:
            - "rathenadb:/var/lib/mysql" # save database to local disk
            - "../../sql-files/:/docker-entrypoint-initdb.d" # initialize db with ./sql-files
        environment:
            MYSQL_ROOT_PASSWORD: ragnarok
            MYSQL_DATABASE: ragnarok
            MYSQL_USER: ragnarok
            MYSQL_PASSWORD: ragnarok

    login:
        image: "rathena/${mod:-rathena-renewal-vip}:${version:-nightly}"
        command: "./login-server"
        restart: always
        ports:
            - "6900:6900" # login server
        volumes:
            - "./asset/inter_conf.txt:/rathena/conf/import/inter_conf.txt" # load db connection
            - "./asset/char_conf.txt:/rathena/conf/import/char_conf.txt"   #localdev login-char relation
            - "./asset/map_conf.txt:/rathena/conf/import/map_conf.txt"     #localdev char-map relation
        depends_on:
            - db
    char:
        image: "rathena/${mod:-rathena-renewal-vip}:${version:-nightly}"
        command: "./char-server"
        restart: always
        ports:
            - "6121:6121" # char server
        volumes:
            - "./asset/inter_conf.txt:/rathena/conf/import/inter_conf.txt" # load db connection
            - "./asset/char_conf.txt:/rathena/conf/import/char_conf.txt"   #localdev login-char relation
            - "./asset/map_conf.txt:/rathena/conf/import/map_conf.txt"     #localdev char-map relation
        depends_on:
            - login
    map:
        image: "rathena/${mod:-rathena-renewal-vip}:${version:-nightly}"
        command: "./map-server"
        restart: always
        ports:
            - "5121:5121" # map server
        volumes:
            - "./asset/inter_conf.txt:/rathena/conf/import/inter_conf.txt" # load db connection
            - "./asset/char_conf.txt:/rathena/conf/import/char_conf.txt"   #localdev login-char relation
            - "./asset/map_conf.txt:/rathena/conf/import/map_conf.txt"     #localdev char-map relation
        depends_on:
            - char

volumes:
    rathenadb:
